# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
use_frameworks!

target ‘Mirkofalowka’ do

pod ‘Alamofire’, '~> 4.0'
pod 'CryptoSwift'
pod 'ObjectMapper'
pod 'AlamofireObjectMapper'
pod 'SDWebImage'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

end

