# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
use_frameworks!

target ‘Mirkofalowka’ do

pod ‘Alamofire’
pod 'CryptoSwift'
pod 'ObjectMapper'
pod 'AlamofireObjectMapper'
pod 'SDWebImage'

end

